### ISSUE TITLE
{project} click to enlarge images

### ISSUE THREAD

**Issue by johnkeough** [johnkeough/johnkeough.github.io#2]

**Comment by saulbaizman** [comment]
John,

We're going to do an in-class demo on Friday that will show you how to create a lightbox using a jQuery plugin called [fancybox](http://fancyapps.com/fancybox/3/).

Saul

**Comment by johnkeough** [comment]
Awesome thanks!

**Comment by saulbaizman** [comment]
Ready to close this issue?
